//
// Created by Zach Cobell on 5/31/22.
//

#ifndef METGET_SRC_DATA_SOURCES_GRIDDEDDATATYPES_H_
#define METGET_SRC_DATA_SOURCES_GRIDDEDDATATYPES_H_

namespace MetBuild {

namespace GriddedDataTypes {
enum SOURCE_SUBTYPE { GRIB, COAMPS };
enum TYPE { WIND_PRESSURE, TEMPERATURE, HUMIDITY, RAINFALL, ICE };
enum VARIABLES {
  VAR_PRESSURE,
  VAR_U10,
  VAR_V10,
  VAR_TEMPERATURE,
  VAR_HUMIDITY,
  VAR_RAINFALL,
  VAR_ICE
};
}

}

#endif  // METGET_SRC_DATA_SOURCES_GRIDDEDDATATYPES_H_
