//
// Created by zcobell on 10/19/22.
//

#ifndef METGET_COORDINATECONVENTION_H
#define METGET_COORDINATECONVENTION_H

namespace MetBuild {

enum COORDINATE_CONVENTION { CONVENTION_180, CONVENTION_360 };

}
#endif  // METGET_COORDINATECONVENTION_H
