NHC_IAN_BESTRACK_JSON = {
    "statusCode": 200,
    "body": {
        "geojson": {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-46.6, 9.9]},
                    "properties": {
                        "time_utc": "2022-09-19T12:00:00",
                        "max_wind_speed_mph": 23.02,
                        "minimum_sea_level_pressure_mb": 1012.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-48.2, 10.1]},
                    "properties": {
                        "time_utc": "2022-09-19T18:00:00",
                        "max_wind_speed_mph": 17.26,
                        "minimum_sea_level_pressure_mb": 1012.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-49.8, 10.0]},
                    "properties": {
                        "time_utc": "2022-09-20T00:00:00",
                        "max_wind_speed_mph": 23.02,
                        "minimum_sea_level_pressure_mb": 1012.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-51.9, 10.2]},
                    "properties": {
                        "time_utc": "2022-09-20T06:00:00",
                        "max_wind_speed_mph": 28.77,
                        "minimum_sea_level_pressure_mb": 1012.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-55.0, 10.0]},
                    "properties": {
                        "time_utc": "2022-09-20T12:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1010.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-56.0, 10.1]},
                    "properties": {
                        "time_utc": "2022-09-20T18:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1009.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-56.6, 10.2]},
                    "properties": {
                        "time_utc": "2022-09-21T00:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1009.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-57.8, 10.2]},
                    "properties": {
                        "time_utc": "2022-09-21T06:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1009.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-59.5, 10.5]},
                    "properties": {
                        "time_utc": "2022-09-21T12:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1007.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-61.4, 10.9]},
                    "properties": {
                        "time_utc": "2022-09-21T18:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1007.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-62.8, 11.2]},
                    "properties": {
                        "time_utc": "2022-09-22T00:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1007.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-64.1, 11.3]},
                    "properties": {
                        "time_utc": "2022-09-22T06:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1007.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-65.1, 11.7]},
                    "properties": {
                        "time_utc": "2022-09-22T12:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1007.0,
                        "radius_to_max_wind_nmi": 90.0,
                        "storm_class": "DB",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-66.3, 12.3]},
                    "properties": {
                        "time_utc": "2022-09-22T18:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1006.0,
                        "radius_to_max_wind_nmi": 70.0,
                        "storm_class": "LO",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-67.2, 12.9]},
                    "properties": {
                        "time_utc": "2022-09-23T00:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1006.0,
                        "radius_to_max_wind_nmi": 70.0,
                        "storm_class": "LO",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-68.1, 13.7]},
                    "properties": {
                        "time_utc": "2022-09-23T06:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1006.0,
                        "radius_to_max_wind_nmi": 60.0,
                        "storm_class": "TD",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-69.5, 14.1]},
                    "properties": {
                        "time_utc": "2022-09-23T12:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1006.0,
                        "radius_to_max_wind_nmi": 60.0,
                        "storm_class": "TD",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-70.6, 14.6]},
                    "properties": {
                        "time_utc": "2022-09-23T18:00:00",
                        "max_wind_speed_mph": 34.52,
                        "minimum_sea_level_pressure_mb": 1006.0,
                        "radius_to_max_wind_nmi": 60.0,
                        "storm_class": "TD",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-71.6, 14.8]},
                    "properties": {
                        "time_utc": "2022-09-24T00:00:00",
                        "max_wind_speed_mph": 40.28,
                        "minimum_sea_level_pressure_mb": 1005.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-72.8, 14.7]},
                    "properties": {
                        "time_utc": "2022-09-24T06:00:00",
                        "max_wind_speed_mph": 40.28,
                        "minimum_sea_level_pressure_mb": 1005.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-74.5, 14.4]},
                    "properties": {
                        "time_utc": "2022-09-24T12:00:00",
                        "max_wind_speed_mph": 46.03,
                        "minimum_sea_level_pressure_mb": 1003.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-76.2, 14.4]},
                    "properties": {
                        "time_utc": "2022-09-24T18:00:00",
                        "max_wind_speed_mph": 46.03,
                        "minimum_sea_level_pressure_mb": 1003.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-77.2, 14.6]},
                    "properties": {
                        "time_utc": "2022-09-25T00:00:00",
                        "max_wind_speed_mph": 51.79,
                        "minimum_sea_level_pressure_mb": 1002.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-78.3, 14.6]},
                    "properties": {
                        "time_utc": "2022-09-25T06:00:00",
                        "max_wind_speed_mph": 51.79,
                        "minimum_sea_level_pressure_mb": 1003.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.4, 15.0]},
                    "properties": {
                        "time_utc": "2022-09-25T12:00:00",
                        "max_wind_speed_mph": 46.03,
                        "minimum_sea_level_pressure_mb": 1003.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.0, 15.7]},
                    "properties": {
                        "time_utc": "2022-09-25T18:00:00",
                        "max_wind_speed_mph": 46.03,
                        "minimum_sea_level_pressure_mb": 1003.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.9, 16.9]},
                    "properties": {
                        "time_utc": "2022-09-26T00:00:00",
                        "max_wind_speed_mph": 57.54,
                        "minimum_sea_level_pressure_mb": 991.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.9, 16.9]},
                    "properties": {
                        "time_utc": "2022-09-26T00:00:00",
                        "max_wind_speed_mph": 57.54,
                        "minimum_sea_level_pressure_mb": 991.0,
                        "radius_to_max_wind_nmi": 30.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.7, 17.7]},
                    "properties": {
                        "time_utc": "2022-09-26T06:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 985.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.7, 17.7]},
                    "properties": {
                        "time_utc": "2022-09-26T06:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 985.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.7, 17.7]},
                    "properties": {
                        "time_utc": "2022-09-26T06:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 985.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.4, 18.7]},
                    "properties": {
                        "time_utc": "2022-09-26T12:00:00",
                        "max_wind_speed_mph": 80.55,
                        "minimum_sea_level_pressure_mb": 981.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.4, 18.7]},
                    "properties": {
                        "time_utc": "2022-09-26T12:00:00",
                        "max_wind_speed_mph": 80.55,
                        "minimum_sea_level_pressure_mb": 981.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.4, 18.7]},
                    "properties": {
                        "time_utc": "2022-09-26T12:00:00",
                        "max_wind_speed_mph": 80.55,
                        "minimum_sea_level_pressure_mb": 981.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.0, 19.7]},
                    "properties": {
                        "time_utc": "2022-09-26T18:00:00",
                        "max_wind_speed_mph": 92.06,
                        "minimum_sea_level_pressure_mb": 976.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.0, 19.7]},
                    "properties": {
                        "time_utc": "2022-09-26T18:00:00",
                        "max_wind_speed_mph": 92.06,
                        "minimum_sea_level_pressure_mb": 976.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.0, 19.7]},
                    "properties": {
                        "time_utc": "2022-09-26T18:00:00",
                        "max_wind_speed_mph": 92.06,
                        "minimum_sea_level_pressure_mb": 976.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.3, 20.8]},
                    "properties": {
                        "time_utc": "2022-09-27T00:00:00",
                        "max_wind_speed_mph": 97.82,
                        "minimum_sea_level_pressure_mb": 965.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.3, 20.8]},
                    "properties": {
                        "time_utc": "2022-09-27T00:00:00",
                        "max_wind_speed_mph": 97.82,
                        "minimum_sea_level_pressure_mb": 965.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.3, 20.8]},
                    "properties": {
                        "time_utc": "2022-09-27T00:00:00",
                        "max_wind_speed_mph": 97.82,
                        "minimum_sea_level_pressure_mb": 965.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.6, 21.8]},
                    "properties": {
                        "time_utc": "2022-09-27T06:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 956.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.6, 21.8]},
                    "properties": {
                        "time_utc": "2022-09-27T06:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 956.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.6, 21.8]},
                    "properties": {
                        "time_utc": "2022-09-27T06:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 956.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.7, 22.2]},
                    "properties": {
                        "time_utc": "2022-09-27T08:00:00",
                        "max_wind_speed_mph": 126.59,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.7, 22.2]},
                    "properties": {
                        "time_utc": "2022-09-27T08:00:00",
                        "max_wind_speed_mph": 126.59,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.7, 22.2]},
                    "properties": {
                        "time_utc": "2022-09-27T08:00:00",
                        "max_wind_speed_mph": 126.59,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.6, 22.6]},
                    "properties": {
                        "time_utc": "2022-09-27T12:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 963.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.6, 22.6]},
                    "properties": {
                        "time_utc": "2022-09-27T12:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 963.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.6, 22.6]},
                    "properties": {
                        "time_utc": "2022-09-27T12:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 963.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.3, 23.5]},
                    "properties": {
                        "time_utc": "2022-09-27T18:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 951.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.3, 23.5]},
                    "properties": {
                        "time_utc": "2022-09-27T18:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 951.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.3, 23.5]},
                    "properties": {
                        "time_utc": "2022-09-27T18:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 951.0,
                        "radius_to_max_wind_nmi": 15.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.0, 24.4]},
                    "properties": {
                        "time_utc": "2022-09-28T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.0, 24.4]},
                    "properties": {
                        "time_utc": "2022-09-28T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.0, 24.4]},
                    "properties": {
                        "time_utc": "2022-09-28T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.9, 25.2]},
                    "properties": {
                        "time_utc": "2022-09-28T06:00:00",
                        "max_wind_speed_mph": 138.09,
                        "minimum_sea_level_pressure_mb": 945.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.9, 25.2]},
                    "properties": {
                        "time_utc": "2022-09-28T06:00:00",
                        "max_wind_speed_mph": 138.09,
                        "minimum_sea_level_pressure_mb": 945.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.9, 25.2]},
                    "properties": {
                        "time_utc": "2022-09-28T06:00:00",
                        "max_wind_speed_mph": 138.09,
                        "minimum_sea_level_pressure_mb": 945.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.7, 26.0]},
                    "properties": {
                        "time_utc": "2022-09-28T12:00:00",
                        "max_wind_speed_mph": 155.36,
                        "minimum_sea_level_pressure_mb": 937.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.7, 26.0]},
                    "properties": {
                        "time_utc": "2022-09-28T12:00:00",
                        "max_wind_speed_mph": 155.36,
                        "minimum_sea_level_pressure_mb": 937.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.7, 26.0]},
                    "properties": {
                        "time_utc": "2022-09-28T12:00:00",
                        "max_wind_speed_mph": 155.36,
                        "minimum_sea_level_pressure_mb": 937.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.4, 26.6]},
                    "properties": {
                        "time_utc": "2022-09-28T18:00:00",
                        "max_wind_speed_mph": 155.36,
                        "minimum_sea_level_pressure_mb": 938.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.4, 26.6]},
                    "properties": {
                        "time_utc": "2022-09-28T18:00:00",
                        "max_wind_speed_mph": 155.36,
                        "minimum_sea_level_pressure_mb": 938.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.4, 26.6]},
                    "properties": {
                        "time_utc": "2022-09-28T18:00:00",
                        "max_wind_speed_mph": 155.36,
                        "minimum_sea_level_pressure_mb": 938.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.7, 27.2]},
                    "properties": {
                        "time_utc": "2022-09-29T00:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 960.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.7, 27.2]},
                    "properties": {
                        "time_utc": "2022-09-29T00:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 960.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.7, 27.2]},
                    "properties": {
                        "time_utc": "2022-09-29T00:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 960.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.1, 27.7]},
                    "properties": {
                        "time_utc": "2022-09-29T06:00:00",
                        "max_wind_speed_mph": 69.05,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.1, 27.7]},
                    "properties": {
                        "time_utc": "2022-09-29T06:00:00",
                        "max_wind_speed_mph": 69.05,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 20.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.6, 28.4]},
                    "properties": {
                        "time_utc": "2022-09-29T12:00:00",
                        "max_wind_speed_mph": 69.05,
                        "minimum_sea_level_pressure_mb": 987.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.6, 28.4]},
                    "properties": {
                        "time_utc": "2022-09-29T12:00:00",
                        "max_wind_speed_mph": 69.05,
                        "minimum_sea_level_pressure_mb": 987.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.1, 28.9]},
                    "properties": {
                        "time_utc": "2022-09-29T18:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.1, 28.9]},
                    "properties": {
                        "time_utc": "2022-09-29T18:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.1, 28.9]},
                    "properties": {
                        "time_utc": "2022-09-29T18:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.4, 29.6]},
                    "properties": {
                        "time_utc": "2022-09-30T00:00:00",
                        "max_wind_speed_mph": 80.55,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.4, 29.6]},
                    "properties": {
                        "time_utc": "2022-09-30T00:00:00",
                        "max_wind_speed_mph": 80.55,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.4, 29.6]},
                    "properties": {
                        "time_utc": "2022-09-30T00:00:00",
                        "max_wind_speed_mph": 80.55,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.1, 30.3]},
                    "properties": {
                        "time_utc": "2022-09-30T06:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 984.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.1, 30.3]},
                    "properties": {
                        "time_utc": "2022-09-30T06:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 984.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.1, 30.3]},
                    "properties": {
                        "time_utc": "2022-09-30T06:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 984.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.0, 31.5]},
                    "properties": {
                        "time_utc": "2022-09-30T12:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 980.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.0, 31.5]},
                    "properties": {
                        "time_utc": "2022-09-30T12:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 980.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.0, 31.5]},
                    "properties": {
                        "time_utc": "2022-09-30T12:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 980.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.2, 33.3]},
                    "properties": {
                        "time_utc": "2022-09-30T18:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 977.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.2, 33.3]},
                    "properties": {
                        "time_utc": "2022-09-30T18:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 977.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.2, 33.3]},
                    "properties": {
                        "time_utc": "2022-09-30T18:00:00",
                        "max_wind_speed_mph": 86.31,
                        "minimum_sea_level_pressure_mb": 977.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.3, 34.4]},
                    "properties": {
                        "time_utc": "2022-10-01T00:00:00",
                        "max_wind_speed_mph": 57.54,
                        "minimum_sea_level_pressure_mb": 990.0,
                        "radius_to_max_wind_nmi": 80.0,
                        "storm_class": "EX",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.3, 34.4]},
                    "properties": {
                        "time_utc": "2022-10-01T00:00:00",
                        "max_wind_speed_mph": 57.54,
                        "minimum_sea_level_pressure_mb": 990.0,
                        "radius_to_max_wind_nmi": 80.0,
                        "storm_class": "EX",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.7, 35.3]},
                    "properties": {
                        "time_utc": "2022-10-01T06:00:00",
                        "max_wind_speed_mph": 17.26,
                        "minimum_sea_level_pressure_mb": 1005.0,
                        "radius_to_max_wind_nmi": 200.0,
                        "storm_class": "EX",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.9, 35.8]},
                    "properties": {
                        "time_utc": "2022-10-01T12:00:00",
                        "max_wind_speed_mph": 23.02,
                        "minimum_sea_level_pressure_mb": 1005.0,
                        "radius_to_max_wind_nmi": 400.0,
                        "storm_class": "EX",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-79.2, 36.7]},
                    "properties": {
                        "time_utc": "2022-10-01T18:00:00",
                        "max_wind_speed_mph": 23.02,
                        "minimum_sea_level_pressure_mb": 1008.0,
                        "radius_to_max_wind_nmi": 55.0,
                        "storm_class": "EX",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-78.5, 37.3]},
                    "properties": {
                        "time_utc": "2022-10-02T00:00:00",
                        "max_wind_speed_mph": 17.26,
                        "minimum_sea_level_pressure_mb": 1009.0,
                        "radius_to_max_wind_nmi": 40.0,
                        "storm_class": "EX",
                    },
                },
            ],
        }
    },
}

NHC_IAN_FORECAST_JSON = {
    "statusCode": 200,
    "body": {
        "geojson": {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.9, 16.9]},
                    "properties": {
                        "time_utc": "2022-09-26T00:00:00",
                        "max_wind_speed_mph": 57.54,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-80.9, 16.9]},
                    "properties": {
                        "time_utc": "2022-09-26T00:00:00",
                        "max_wind_speed_mph": 57.54,
                        "minimum_sea_level_pressure_mb": 986.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.4, 17.3]},
                    "properties": {
                        "time_utc": "2022-09-26T03:00:00",
                        "max_wind_speed_mph": 63.29,
                        "minimum_sea_level_pressure_mb": 989.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-81.4, 17.3]},
                    "properties": {
                        "time_utc": "2022-09-26T03:00:00",
                        "max_wind_speed_mph": 63.29,
                        "minimum_sea_level_pressure_mb": 989.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "TS",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.3, 18.7]},
                    "properties": {
                        "time_utc": "2022-09-26T12:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 982.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.3, 18.7]},
                    "properties": {
                        "time_utc": "2022-09-26T12:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 982.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.3, 18.7]},
                    "properties": {
                        "time_utc": "2022-09-26T12:00:00",
                        "max_wind_speed_mph": 74.8,
                        "minimum_sea_level_pressure_mb": 982.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.5, 20.8]},
                    "properties": {
                        "time_utc": "2022-09-27T00:00:00",
                        "max_wind_speed_mph": 97.82,
                        "minimum_sea_level_pressure_mb": 965.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.5, 20.8]},
                    "properties": {
                        "time_utc": "2022-09-27T00:00:00",
                        "max_wind_speed_mph": 97.82,
                        "minimum_sea_level_pressure_mb": 965.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.5, 20.8]},
                    "properties": {
                        "time_utc": "2022-09-27T00:00:00",
                        "max_wind_speed_mph": 97.82,
                        "minimum_sea_level_pressure_mb": 965.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-84.0, 22.7]},
                    "properties": {
                        "time_utc": "2022-09-27T12:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 952.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-84.0, 22.7]},
                    "properties": {
                        "time_utc": "2022-09-27T12:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 952.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-84.0, 22.7]},
                    "properties": {
                        "time_utc": "2022-09-27T12:00:00",
                        "max_wind_speed_mph": 115.08,
                        "minimum_sea_level_pressure_mb": 952.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-84.1, 24.7]},
                    "properties": {
                        "time_utc": "2022-09-28T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-84.1, 24.7]},
                    "properties": {
                        "time_utc": "2022-09-28T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-84.1, 24.7]},
                    "properties": {
                        "time_utc": "2022-09-28T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 947.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.8, 26.2]},
                    "properties": {
                        "time_utc": "2022-09-28T12:00:00",
                        "max_wind_speed_mph": 132.34,
                        "minimum_sea_level_pressure_mb": 939.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.8, 26.2]},
                    "properties": {
                        "time_utc": "2022-09-28T12:00:00",
                        "max_wind_speed_mph": 132.34,
                        "minimum_sea_level_pressure_mb": 939.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.5, 27.6]},
                    "properties": {
                        "time_utc": "2022-09-29T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 945.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.5, 27.6]},
                    "properties": {
                        "time_utc": "2022-09-29T00:00:00",
                        "max_wind_speed_mph": 120.83,
                        "minimum_sea_level_pressure_mb": 945.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.2, 29.0]},
                    "properties": {
                        "time_utc": "2022-09-30T00:00:00",
                        "max_wind_speed_mph": 92.06,
                        "minimum_sea_level_pressure_mb": 948.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-83.2, 29.0]},
                    "properties": {
                        "time_utc": "2022-09-30T00:00:00",
                        "max_wind_speed_mph": 92.06,
                        "minimum_sea_level_pressure_mb": 948.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "HU",
                    },
                },
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [-82.5, 32.0]},
                    "properties": {
                        "time_utc": "2022-10-01T00:00:00",
                        "max_wind_speed_mph": 46.03,
                        "minimum_sea_level_pressure_mb": 974.0,
                        "radius_to_max_wind_nmi": 0.0,
                        "storm_class": "TS",
                    },
                },
            ],
        }
    },
}
