CREATE DATABASE metget;
USE metget;

CREATE TABLE gfs_ncep(id INTEGER PRIMARY KEY AUTO_INCREMENT, forecastcycle DATETIME NOT NULL, forecasttime DATETIME NOT NULL, tau INTEGER NOT NULL, filepath VARCHAR(256) NOT NULL, url VARCHAR(256) NOT NULL, accessed DATETIME NOT NULL);

CREATE TABLE gefs_fcst(id INTEGER PRIMARY KEY AUTO_INCREMENT, forecastcycle DATETIME NOT NULL, forecasttime DATETIME NOT NULL, ensemble_member VARCHAR(32) NOT NULL, tau INTEGER NOT NULL, filepath VARCHAR(256) NOT NULL, url VARCHAR(256) NOT NULL, accessed DATETIME NOT NULL);

CREATE TABLE hwrf(id INTEGER PRIMARY KEY AUTO_INCREMENT, stormname VARCHAR(256) NOT NULL, forecastcycle DATETIME NOT NULL, forecasttime DATETIME NOT NULL, tau INTEGER NOT NULL, filepath VARCHAR(256) NOT NULL, url VARCHAR(256) NOT NULL, accessed DATETIME NOT NULL);

CREATE TABLE nam_ncep(id INTEGER PRIMARY KEY AUTO_INCREMENT, forecastcycle DATETIME NOT NULL, forecasttime DATETIME NOT NULL, tau INTEGER NOT NULL, filepath VARCHAR(256) NOT NULL, url VARCHAR(256) NOT NULL, accessed DATETIME NOT NULL);

CREATE TABLE nhc_btk(id INTEGER PRIMARY KEY AUTO_INCREMENT, storm_year INTEGER NOT NULL, basin VARCHAR(256) NOT NULL, storm INTEGER NOT NULL, advisory_start DATETIME NOT NULL, advisory_end DATETIME NOT NULL, advisory_duration_hr INT NOT NULL, filepath VARCHAR(256) NOT NULL, md5 VARCHAR(32) NOT NULL, accessed DATETIME NOT NULL, geojson MEDIUMTEXT NOT NULL );

CREATE TABLE nhc_fcst(id INTEGER PRIMARY KEY AUTO_INCREMENT, storm_year INTEGER NOT NULL, basin VARCHAR(256) NOT NULL, storm INTEGER NOT NULL, advisory VARCHAR(256) NOT NULL, advisory_start DATETIME NOT NULL, advisory_end DATETIME NOT NULL, advisory_duration_hr INT NOT NULL, filepath VARCHAR(256) NOT NULL, md5 VARCHAR(32) NOT NULL, accessed DATETIME NOT NULL, geojson MEDIUMTEXT NOT NULL);

CREATE TABLE coamps_tc(id INTEGER PRIMARY KEY AUTO_INCREMENT, stormname VARCHAR(256) NOT NULL, forecastcycle DATETIME NOT NULL, forecasttime DATETIME NOT NULL, tau INTEGER NOT NULL, filepath VARCHAR(512) NOT NULL, accessed DATETIME NOT NULL);

CREATE TABLE hrrr_ncep(id INTEGER PRIMARY KEY AUTO_INCREMENT, forecastcycle DATETIME NOT NULL, forecasttime DATETIME NOT NULL, tau INTEGER NOT NULL, filepath VARCHAR(256) NOT NULL, url VARCHAR(256) NOT NULL, accessed DATETIME NOT NULL);

CREATE TABLE hrrr_alaska_ncep(id INTEGER PRIMARY KEY AUTO_INCREMENT, forecastcycle DATETIME NOT NULL, forecasttime DATETIME NOT NULL, tau INTEGER NOT NULL, filepath VARCHAR(256) NOT NULL, url VARCHAR(256) NOT NULL, accessed DATETIME NOT NULL);
